package geminiconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	domainprofile "github.com/kiddingbaby/agx/internal/domain/profile"
)

func TestSyncUpdatesEnvWithoutAutoBackup(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := "KEEP_ME=\"1\"\n"
	if err := os.WriteFile(envPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(envPath, backupsDir)
	result, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-c",
		BaseURL:   "https://relay.example/gemini",
		APIKey:    "sk-c",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	})
	if err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if result.ConfigPath != envPath {
		t.Fatalf("ConfigPath = %q, want %q", result.ConfigPath, envPath)
	}

	got, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("ReadFile(env) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "GEMINI_API_KEY=\"sk-c\"") {
		t.Fatalf(".env=%q want GEMINI_API_KEY", text)
	}
	if !strings.Contains(text, "GOOGLE_GEMINI_BASE_URL=\"https://relay.example/gemini\"") {
		t.Fatalf(".env=%q want GOOGLE_GEMINI_BASE_URL", text)
	}
}

func TestSnapshotCreateBackupAndRestore(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	original := "KEEP_ME=\"1\"\n"
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(envPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(envPath, backupsDir)
	snapshot, err := syncer.Snapshot()
	if err != nil {
		t.Fatalf("Snapshot() error = %v", err)
	}
	backupPath, err := syncer.CreateBackup("before-gemini-sync", snapshot.Content)
	if err != nil {
		t.Fatalf("CreateBackup() error = %v", err)
	}
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-c", BaseURL: "https://relay.example", APIKey: "sk-c"}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if _, err := syncer.Restore(backupPath); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}

	got, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("ReadFile(env) error = %v", err)
	}
	if string(got) != original {
		t.Fatalf("restored env = %q, want %q", string(got), original)
	}
}

func TestRemoveConfigRemovesOnlyManagedBlock(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	syncer := NewSyncer(envPath, filepath.Join(dir, ".config", "agx", "backups"))
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	content := strings.Join([]string{
		"KEEP=1",
		"",
		beginMarker,
		"# Generated by AGX. Edit the AGX profile instead of this block.",
		"GEMINI_API_KEY=\"sk-a\"",
		"GOOGLE_GEMINI_BASE_URL=\"https://relay.example/v1\"",
		endMarker,
		"",
	}, "\n")
	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := syncer.RemoveConfig(); err != nil {
		t.Fatalf("RemoveConfig() error = %v", err)
	}

	got, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("ReadFile(env) error = %v", err)
	}
	if string(got) != "KEEP=1\n" {
		t.Fatalf("env=%q want KEEP=1 only", string(got))
	}
}

func TestRemoveConfigDeletesPureManagedEnv(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	syncer := NewSyncer(envPath, filepath.Join(dir, ".config", "agx", "backups"))
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	content := renderManagedBlock(domainprofile.Profile{
		Name:    "relay-a",
		BaseURL: "https://relay.example/v1",
		APIKey:  "sk-a",
	})
	if err := os.WriteFile(envPath, []byte(content+"\n"), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := syncer.RemoveConfig(); err != nil {
		t.Fatalf("RemoveConfig() error = %v", err)
	}
	if _, err := os.Stat(envPath); !os.IsNotExist(err) {
		t.Fatalf("env still exists, err = %v", err)
	}
}
