package geminiconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/kiddingbaby/agx/internal/adapters/fileutil"
	domainprofile "github.com/kiddingbaby/agx/internal/domain/profile"
	"github.com/kiddingbaby/agx/internal/ports"
)

const (
	beginMarker = "# >>> AGX managed Gemini env >>>"
	endMarker   = "# <<< AGX managed Gemini env <<<"
)

var _ ports.GeminiSyncer = (*Syncer)(nil)

type Syncer struct {
	envPath    string
	backupsDir string
}

func NewSyncer(envPath, backupsDir string) *Syncer {
	return &Syncer{
		envPath:    envPath,
		backupsDir: filepath.Join(backupsDir, "gemini"),
	}
}

func (s *Syncer) Sync(profile domainprofile.Profile) (*ports.GeminiSyncResult, error) {
	existing, _, err := readIfExists(s.envPath)
	if err != nil {
		return nil, err
	}

	next := appendManagedBlock(stripManagedBlock(existing), renderManagedBlock(profile))
	if err := fileutil.AtomicWriteFile(s.envPath, []byte(next), 0600); err != nil {
		return nil, err
	}

	return &ports.GeminiSyncResult{
		ConfigPath: s.envPath,
	}, nil
}

func (s *Syncer) Restore(backupPath string) (string, error) {
	data, err := os.ReadFile(backupPath)
	if err != nil {
		return "", err
	}
	if err := fileutil.AtomicWriteFile(s.envPath, data, 0600); err != nil {
		return "", err
	}
	return s.envPath, nil
}

func (s *Syncer) Snapshot() (*ports.AgentConfigSnapshot, error) {
	content, exists, err := readIfExists(s.envPath)
	if err != nil {
		return nil, err
	}
	return &ports.AgentConfigSnapshot{
		ConfigPath: s.envPath,
		Exists:     exists,
		Content:    []byte(content),
	}, nil
}

func (s *Syncer) CreateBackup(id string, content []byte) (string, error) {
	if err := os.MkdirAll(s.backupsDir, 0700); err != nil {
		return "", err
	}
	name := fmt.Sprintf(".env.%s.bak", id)
	path := filepath.Join(s.backupsDir, name)
	if err := fileutil.AtomicWriteFile(path, content, 0600); err != nil {
		return "", err
	}
	return path, nil
}

func (s *Syncer) RemoveConfig() (string, error) {
	existing, exists, err := readIfExists(s.envPath)
	if err != nil {
		return "", err
	}
	if !exists {
		return s.envPath, nil
	}

	next := strings.TrimSpace(stripManagedBlock(existing))
	if next == "" {
		if err := os.Remove(s.envPath); err != nil && !os.IsNotExist(err) {
			return "", err
		}
		return s.envPath, nil
	}
	next += "\n"
	if err := fileutil.AtomicWriteFile(s.envPath, []byte(next), 0600); err != nil {
		return "", err
	}
	return s.envPath, nil
}

func (s *Syncer) DeleteBackup(backupPath string) error {
	if strings.TrimSpace(backupPath) == "" {
		return nil
	}
	if err := os.Remove(backupPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func readIfExists(path string) (string, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, err
	}
	return string(data), true, nil
}

func stripManagedBlock(content string) string {
	start := strings.Index(content, beginMarker)
	if start < 0 {
		return content
	}
	end := strings.Index(content[start:], endMarker)
	if end < 0 {
		return content[:start]
	}
	end += start + len(endMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return content[:start] + content[end:]
}

func appendManagedBlock(content, block string) string {
	content = strings.TrimRight(content, "\n")
	if content == "" {
		return block + "\n"
	}
	return content + "\n\n" + block + "\n"
}

func renderManagedBlock(profile domainprofile.Profile) string {
	var b strings.Builder
	b.WriteString(beginMarker)
	b.WriteString("\n")
	b.WriteString("# Generated by AGX. Edit the AGX profile instead of this block.\n")
	b.WriteString("GEMINI_API_KEY=")
	b.WriteString(strconv.Quote(profile.APIKey))
	b.WriteString("\n")
	b.WriteString("GOOGLE_GEMINI_BASE_URL=")
	b.WriteString(strconv.Quote(profile.BaseURL))
	b.WriteString("\n")
	b.WriteString(endMarker)
	return b.String()
}
