package geminiconfig

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	domainprofile "github.com/kiddingbaby/agx/internal/domain/profile"
)

func TestSyncUpdatesEnvWithoutAutoBackup(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := "KEEP_ME=\"1\"\n"
	if err := os.WriteFile(envPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(envPath, backupsDir)
	result, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-c",
		BaseURL:   "https://relay.example/gemini/v1",
		APIKey:    "sk-c",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	})
	if err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if result.ConfigPath != envPath {
		t.Fatalf("ConfigPath = %q, want %q", result.ConfigPath, envPath)
	}

	got, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("ReadFile(env) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "GEMINI_API_KEY=\"sk-c\"") {
		t.Fatalf(".env=%q want GEMINI_API_KEY", text)
	}
	if !strings.Contains(text, "GOOGLE_GEMINI_BASE_URL=\"https://relay.example/gemini\"") {
		t.Fatalf(".env=%q want GOOGLE_GEMINI_BASE_URL", text)
	}

	settingsPath := filepath.Join(dir, ".gemini", "settings.json")
	settings, err := os.ReadFile(settingsPath)
	if err != nil {
		t.Fatalf("ReadFile(settings) error = %v", err)
	}
	if !strings.Contains(string(settings), `"selectedType": "gemini-api-key"`) {
		t.Fatalf("settings.json=%q want gemini-api-key auth", string(settings))
	}
	if !strings.Contains(string(settings), `"sandbox": false`) {
		t.Fatalf("settings.json=%q want sandbox false", string(settings))
	}
}

func TestSnapshotCreateBackupAndRestore(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	settingsPath := filepath.Join(dir, ".gemini", "settings.json")
	original := "KEEP_ME=\"1\"\n"
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(envPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if err := os.WriteFile(settingsPath, []byte("{\"keep\":\"me\"}\n"), 0600); err != nil {
		t.Fatalf("WriteFile(settings) error = %v", err)
	}

	syncer := NewSyncer(envPath, backupsDir)
	snapshot, err := syncer.Snapshot()
	if err != nil {
		t.Fatalf("Snapshot() error = %v", err)
	}
	backupPath, err := syncer.CreateBackup("before-gemini-sync", snapshot.Content)
	if err != nil {
		t.Fatalf("CreateBackup() error = %v", err)
	}
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-c", BaseURL: "https://relay.example", APIKey: "sk-c"}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if _, err := syncer.Restore(backupPath); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}

	got, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("ReadFile(env) error = %v", err)
	}
	if string(got) != original {
		t.Fatalf("restored env = %q, want %q", string(got), original)
	}
	settings, err := os.ReadFile(settingsPath)
	if err != nil {
		t.Fatalf("ReadFile(settings) error = %v", err)
	}
	if string(settings) != "{\"keep\":\"me\"}\n" {
		t.Fatalf("restored settings = %q, want original settings", string(settings))
	}
}

func TestRemoveConfigRemovesOnlyManagedBlock(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	syncer := NewSyncer(envPath, filepath.Join(dir, ".config", "agx", "backups"))
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	content := strings.Join([]string{
		"KEEP=1",
		"",
		beginMarker,
		"# Generated by AGX. Edit the AGX profile instead of this block.",
		"GEMINI_API_KEY=\"sk-a\"",
		"GOOGLE_GEMINI_BASE_URL=\"https://relay.example/v1\"",
		endMarker,
		"",
	}, "\n")
	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := syncer.RemoveConfig(); err != nil {
		t.Fatalf("RemoveConfig() error = %v", err)
	}

	got, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("ReadFile(env) error = %v", err)
	}
	if string(got) != "KEEP=1\n" {
		t.Fatalf("env=%q want KEEP=1 only", string(got))
	}
}

func TestRemoveConfigDeletesPureManagedEnv(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	syncer := NewSyncer(envPath, filepath.Join(dir, ".config", "agx", "backups"))
	if err := os.MkdirAll(filepath.Dir(envPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	content := renderManagedBlock(domainprofile.Profile{
		Name:    "relay-a",
		BaseURL: "https://relay.example/v1",
		APIKey:  "sk-a",
	})
	if err := os.WriteFile(envPath, []byte(content+"\n"), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := syncer.RemoveConfig(); err != nil {
		t.Fatalf("RemoveConfig() error = %v", err)
	}
	if _, err := os.Stat(envPath); !os.IsNotExist(err) {
		t.Fatalf("env still exists, err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".gemini", "settings.json")); !os.IsNotExist(err) {
		t.Fatalf("settings still exists, err = %v", err)
	}
}

func TestSnapshotUsesBundleWhenOnlySettingsExists(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, ".gemini", ".env")
	settingsPath := filepath.Join(dir, ".gemini", "settings.json")
	if err := os.MkdirAll(filepath.Dir(envPath), 0o700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(settingsPath, []byte("{\"only\":\"settings\"}\n"), 0o600); err != nil {
		t.Fatalf("WriteFile(settings) error = %v", err)
	}

	syncer := NewSyncer(envPath, filepath.Join(dir, "backups"))
	snapshot, err := syncer.Snapshot()
	if err != nil {
		t.Fatalf("Snapshot() error = %v", err)
	}
	if snapshot == nil || !snapshot.Exists {
		t.Fatalf("Snapshot() = %+v, want existing bundle snapshot", snapshot)
	}
	var bundle struct {
		Format  string            `json:"format"`
		Files   map[string]string `json:"files"`
		Missing []string          `json:"missing"`
	}
	if err := json.Unmarshal(snapshot.Content, &bundle); err != nil {
		t.Fatalf("Unmarshal(snapshot) error = %v", err)
	}
	if bundle.Format != bundleMagic || bundle.Files["settings.json"] != "{\"only\":\"settings\"}\n" {
		t.Fatalf("bundle = %+v, want settings bundle", bundle)
	}
}
