package codexconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	domainprofile "github.com/kiddingbaby/agx/internal/domain/profile"
	"github.com/kiddingbaby/agx/internal/ports"
)

func TestSyncUpdatesCodexConfigWithoutBackupSideEffects(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := "model = \"gpt-5.4\"\nprofile = \"old\"\n"
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	result, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-a",
		BaseURL:   "https://relay.example/v1",
		APIKey:    "sk-a",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}, ports.CodexSyncOptions{})
	if err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if result.ProfileName != "relay-a" {
		t.Fatalf("ProfileName = %q, want relay-a", result.ProfileName)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "profile = \"old\"") {
		t.Fatalf("config=%q want root profile preserved without explicit default", text)
	}
	if !strings.Contains(text, beginMarker) || !strings.Contains(text, "command = \"agx\"") {
		t.Fatalf("config=%q want managed block", text)
	}
	if !strings.Contains(text, "# The rest of this file stays in your original order.") {
		t.Fatalf("config=%q want managed block note", text)
	}
	if !strings.Contains(text, "[model_providers]\n\n[profiles]\n\n[model_providers.\"agx/relay-a\"]\nname = \"relay-a\"") {
		t.Fatalf("config=%q want codex parent tables and provider name", text)
	}
	if !strings.Contains(text, "[profiles.\"relay-a\"]\nmodel_provider = \"agx/relay-a\"") {
		t.Fatalf("config=%q want relay-a profile block", text)
	}
}

func TestSyncPreservesRootProfileCommentAndManagedProfileExtras(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	original := strings.Join([]string{
		"model = \"gpt-5.4\"",
		"profile = \"old\" # keep this comment",
		"approval_policy = \"on-request\"",
		"",
		"[tools]",
		"web_search = true",
		"",
		"[projects.\"/repo\"]",
		"trust_level = \"trusted\"",
		"",
		beginMarker,
		"# Generated by AGX. Edit the AGX profile instead of this block.",
		"[model_providers.\"agx/old\"]",
		"base_url = \"https://old.example/v1\"",
		"wire_api = \"responses\"",
		"",
		"[model_providers.\"agx/old\".auth]",
		"command = \"agx\"",
		"args = [\"__api-key\", \"old\"]",
		"",
		"[profiles.\"old\"]",
		"model_provider = \"agx/old\"",
		"model = \"gpt-5.5\"",
		"model_reasoning_effort = \"high\"",
		endMarker,
		"",
	}, "\n")
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-a",
		BaseURL:   "https://relay.example/v1",
		APIKey:    "sk-a",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if strings.Count(text, beginMarker) != 1 {
		t.Fatalf("managed block count = %d, want 1; config=%q", strings.Count(text, beginMarker), text)
	}
	if !strings.Contains(text, "profile = \"old\" # keep this comment") {
		t.Fatalf("config=%q want preserved root profile comment", text)
	}
	if !strings.Contains(text, "[tools]\nweb_search = true") {
		t.Fatalf("config=%q want tools section preserved", text)
	}
	if !strings.Contains(text, "[projects.\"/repo\"]\ntrust_level = \"trusted\"") {
		t.Fatalf("config=%q want projects section preserved", text)
	}
	if !strings.Contains(text, "[profiles.\"relay-a\"]\nmodel_provider = \"agx/relay-a\"\nmodel = \"gpt-5.5\"\nmodel_reasoning_effort = \"high\"") {
		t.Fatalf("config=%q want preserved managed profile extras", text)
	}
	if !strings.HasSuffix(text, endMarker+"\n") {
		t.Fatalf("config=%q want managed block at file end", text)
	}
}

func TestSyncRemovesDuplicateManagedBlocks(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	managed := strings.Join([]string{
		beginMarker,
		"# old",
		"[profiles.\"old\"]",
		"model_provider = \"agx/old\"",
		endMarker,
	}, "\n")
	content := "profile = \"old\"\n\n" + managed + "\n\n[tools]\nweb_search = true\n\n" + managed + "\n"
	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-a",
		BaseURL:   "https://relay.example/v1",
		APIKey:    "sk-a",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if strings.Count(text, beginMarker) != 1 {
		t.Fatalf("managed block count = %d, want 1; config=%q", strings.Count(text, beginMarker), text)
	}
}

func TestSnapshotCreateBackupAndRestore(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	original := "profile = \"before\"\n"
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	snapshot, err := syncer.Snapshot()
	if err != nil {
		t.Fatalf("Snapshot() error = %v", err)
	}
	if !snapshot.Exists || string(snapshot.Content) != original {
		t.Fatalf("Snapshot() = %+v, want existing original content", snapshot)
	}

	backupPath, err := syncer.CreateBackup("before-codex-sync", snapshot.Content)
	if err != nil {
		t.Fatalf("CreateBackup() error = %v", err)
	}
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-a", BaseURL: "https://relay.example", APIKey: "sk-a"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if _, err := syncer.Restore(backupPath); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	if string(got) != original {
		t.Fatalf("restored config = %q, want %q", string(got), original)
	}
}

func TestSyncPreservesPreviouslyManagedProfiles(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-a", BaseURL: "https://relay-a.example/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("first Sync() error = %v", err)
	}
	if _, err := syncer.Sync(domainprofile.Profile{Name: "linuxdo", BaseURL: "https://linuxdo.example/v1", APIKey: "sk-b"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("second Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "[profiles.\"relay-a\"]\nmodel_provider = \"agx/relay-a\"") {
		t.Fatalf("config=%q want relay-a profile preserved", text)
	}
	if !strings.Contains(text, "[profiles.\"linuxdo\"]\nmodel_provider = \"agx/linuxdo\"") {
		t.Fatalf("config=%q want linuxdo profile present", text)
	}
	if strings.Contains(text, "[profiles.\"agx/relay-a\"]") || strings.Contains(text, "[profiles.\"agx/linuxdo\"]") {
		t.Fatalf("config=%q want bare Codex profile names", text)
	}
}

func TestSyncCanSetExplicitDefaultProfile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(configPath, []byte("profile = \"before\"\n"), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-a", BaseURL: "https://relay-a.example/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{
		DefaultProfileName: "relay-a",
	}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	if !strings.Contains(string(got), "profile = \"relay-a\"") {
		t.Fatalf("config=%q want root default relay-a", string(got))
	}
}

func TestRemoveConfigDeletesManagedFile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	syncer := NewSyncer(configPath, filepath.Join(dir, ".config", "agx", "backups"), "agx")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(configPath, []byte("profile = \"temp\"\n"), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := syncer.RemoveConfig(); err != nil {
		t.Fatalf("RemoveConfig() error = %v", err)
	}
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config still exists, err = %v", err)
	}
}
