package codexconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	domainprofile "github.com/kiddingbaby/agx/internal/domain/profile"
	"github.com/kiddingbaby/agx/internal/ports"
)

func TestSyncUpdatesCodexConfigWithoutBackupSideEffects(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := "model = \"gpt-5.4\"\nprofile = \"old\"\n"
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	result, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-a",
		BaseURL:   "https://relay.example/v1",
		APIKey:    "sk-a",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}, ports.CodexSyncOptions{})
	if err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if result.ProfileName != "agx/relay-a" {
		t.Fatalf("ProfileName = %q, want agx/relay-a", result.ProfileName)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "profile = \"old\"") {
		t.Fatalf("config=%q want root profile preserved without explicit default", text)
	}
	if !strings.Contains(text, beginMarker) || !strings.Contains(text, "command = \"agx\"") {
		t.Fatalf("config=%q want managed block", text)
	}
	if !strings.Contains(text, "# The rest of this file stays in your original order.") {
		t.Fatalf("config=%q want managed block note", text)
	}
	if !strings.Contains(text, "[model_providers]\n\n[profiles]\n\n[model_providers.\"agx/relay-a\"]\nname = \"relay-a\"") {
		t.Fatalf("config=%q want codex parent tables and provider name", text)
	}
	if !strings.Contains(text, "[profiles.\"agx/relay-a\"]\nmodel_provider = \"agx/relay-a\"") {
		t.Fatalf("config=%q want namespaced relay-a profile block", text)
	}
}

func TestSyncAddsV1ToCodexBaseURL(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{
		Name:    "relay-a",
		BaseURL: "https://relay.example",
		APIKey:  "sk-a",
	}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync(no v1) error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "base_url = \"https://relay.example/v1\"") {
		t.Fatalf("config=%q want /v1 appended for codex", text)
	}

	status, err := syncer.Status()
	if err != nil {
		t.Fatalf("Status() error = %v", err)
	}
	if got := status.ManagedProfilesByID["relay-a"].BaseURL; got != "https://relay.example/v1" {
		t.Fatalf("ManagedProfilesByID[relay-a].BaseURL = %q, want https://relay.example/v1", got)
	}

	if _, err := syncer.Sync(domainprofile.Profile{
		Name:    "relay-a",
		BaseURL: "https://relay.example/v1",
		APIKey:  "sk-a",
	}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync(existing v1) error = %v", err)
	}
	got, err = os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config after existing v1) error = %v", err)
	}
	if strings.Contains(string(got), "/v1/v1") {
		t.Fatalf("config=%q should not duplicate /v1", string(got))
	}
}

func TestSyncPreservesRootProfileCommentAndManagedProfileExtras(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	original := strings.Join([]string{
		"model = \"gpt-5.4\"",
		"profile = \"old\" # keep this comment",
		"approval_policy = \"on-request\"",
		"",
		"[tools]",
		"web_search = true",
		"",
		"[projects.\"/repo\"]",
		"trust_level = \"trusted\"",
		"",
		beginMarker,
		"# Generated by AGX. Edit the AGX profile instead of this block.",
		"[model_providers.\"agx/old\"]",
		"base_url = \"https://old.example/v1\"",
		"wire_api = \"responses\"",
		"",
		"[model_providers.\"agx/old\".auth]",
		"command = \"agx\"",
		"args = [\"__api-key\", \"old\"]",
		"",
		"[profiles.\"old\"]",
		"model_provider = \"agx/old\"",
		"model = \"gpt-5.5\"",
		"model_reasoning_effort = \"high\"",
		endMarker,
		"",
	}, "\n")
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-a",
		BaseURL:   "https://relay.example/v1",
		APIKey:    "sk-a",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if strings.Count(text, beginMarker) != 1 {
		t.Fatalf("managed block count = %d, want 1; config=%q", strings.Count(text, beginMarker), text)
	}
	if !strings.Contains(text, "profile = \"agx/old\" # keep this comment") {
		t.Fatalf("config=%q want migrated root profile comment", text)
	}
	if !strings.Contains(text, "[tools]\nweb_search = true") {
		t.Fatalf("config=%q want tools section preserved", text)
	}
	if !strings.Contains(text, "[projects.\"/repo\"]\ntrust_level = \"trusted\"") {
		t.Fatalf("config=%q want projects section preserved", text)
	}
	if !strings.Contains(text, "[profiles.\"agx/relay-a\"]\nmodel_provider = \"agx/relay-a\"\nmodel = \"gpt-5.5\"\nmodel_reasoning_effort = \"high\"") {
		t.Fatalf("config=%q want preserved managed profile extras", text)
	}
	if !strings.HasSuffix(text, endMarker+"\n") {
		t.Fatalf("config=%q want managed block at file end", text)
	}
}

func TestSyncRemovesDuplicateManagedBlocks(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	managed := strings.Join([]string{
		beginMarker,
		"# old",
		"[profiles.\"old\"]",
		"model_provider = \"agx/old\"",
		endMarker,
	}, "\n")
	content := "profile = \"old\"\n\n" + managed + "\n\n[tools]\nweb_search = true\n\n" + managed + "\n"
	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{
		Name:      "relay-a",
		BaseURL:   "https://relay.example/v1",
		APIKey:    "sk-a",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if strings.Count(text, beginMarker) != 1 {
		t.Fatalf("managed block count = %d, want 1; config=%q", strings.Count(text, beginMarker), text)
	}
}

func TestSnapshotCreateBackupAndRestore(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	original := "profile = \"before\"\n"
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	snapshot, err := syncer.Snapshot()
	if err != nil {
		t.Fatalf("Snapshot() error = %v", err)
	}
	if !snapshot.Exists || string(snapshot.Content) != original {
		t.Fatalf("Snapshot() = %+v, want existing original content", snapshot)
	}

	backupPath, err := syncer.CreateBackup("before-codex-sync", snapshot.Content)
	if err != nil {
		t.Fatalf("CreateBackup() error = %v", err)
	}
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-a", BaseURL: "https://relay.example", APIKey: "sk-a"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	if _, err := syncer.Restore(backupPath); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	if string(got) != original {
		t.Fatalf("restored config = %q, want %q", string(got), original)
	}
}

func TestSyncPreservesPreviouslyManagedProfiles(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-a", BaseURL: "https://relay-a.example/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("first Sync() error = %v", err)
	}
	if _, err := syncer.Sync(domainprofile.Profile{Name: "linuxdo", BaseURL: "https://linuxdo.example/v1", APIKey: "sk-b"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("second Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "[profiles.\"agx/relay-a\"]\nmodel_provider = \"agx/relay-a\"") {
		t.Fatalf("config=%q want relay-a profile preserved", text)
	}
	if !strings.Contains(text, "[profiles.\"agx/linuxdo\"]\nmodel_provider = \"agx/linuxdo\"") {
		t.Fatalf("config=%q want linuxdo profile present", text)
	}
	if strings.Contains(text, "[profiles.\"relay-a\"]") || strings.Contains(text, "[profiles.\"linuxdo\"]") {
		t.Fatalf("config=%q want namespaced Codex profile names only", text)
	}
}

func TestSyncRemovesLegacyBareManagedProfiles(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}

	content := strings.Join([]string{
		"model = \"gpt-5.4\"",
		"",
		"[model_providers.manual]",
		"name = \"manual\"",
		"base_url = \"https://manual.example/v1\"",
		"wire_api = \"responses\"",
		"",
		"[profiles.manual]",
		"model_provider = \"manual\"",
		"",
		"[model_providers.ciallo]",
		"name = \"ciallo\"",
		"base_url = \"https://sin.ioll.pp.ua/v1\"",
		"wire_api = \"responses\"",
		"",
		"[model_providers.ciallo.auth]",
		"env_key = \"K_CIALLO\"",
		"",
		"[profiles.ciallo]",
		"model_provider = \"ciallo\"",
		"",
		"[profiles.tmp]",
		"model_provider = \"tmp\"",
		"",
		beginMarker,
		"[model_providers.\"agx/ciallo\"]",
		"name = \"ciallo\"",
		"base_url = \"https://sin.ioll.pp.ua/v1\"",
		"",
		"[profiles.\"agx/ciallo\"]",
		"model_provider = \"agx/ciallo\"",
		"",
		"[model_providers.\"agx/tmp\"]",
		"name = \"tmp\"",
		"base_url = \"https://cpa.019960.xyz/v1\"",
		"",
		"[profiles.\"agx/tmp\"]",
		"model_provider = \"agx/tmp\"",
		endMarker,
	}, "\n")
	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{Name: "ciallo", BaseURL: "https://sin.ioll.pp.ua/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	for _, unwanted := range []string{
		"[model_providers.ciallo]",
		"[model_providers.ciallo.auth]",
		"[profiles.ciallo]",
		"[profiles.tmp]",
	} {
		if strings.Contains(text, unwanted) {
			t.Fatalf("config=%q want legacy section %q removed", text, unwanted)
		}
	}
	for _, wanted := range []string{
		"[model_providers.manual]",
		"[profiles.manual]",
		"[model_providers.\"agx/ciallo\"]",
		"[profiles.\"agx/ciallo\"]",
		"[profiles.\"agx/tmp\"]",
	} {
		if !strings.Contains(text, wanted) {
			t.Fatalf("config=%q want %q preserved", text, wanted)
		}
	}
}

func TestSyncCanSetExplicitDefaultProfile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(configPath, []byte("profile = \"before\"\n"), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{Name: "relay-a", BaseURL: "https://relay-a.example/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{
		DefaultProfileName: "relay-a",
	}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	if !strings.Contains(string(got), "profile = \"agx/relay-a\"") {
		t.Fatalf("config=%q want root default agx/relay-a", string(got))
	}
}

func TestSyncUsesNamespacedProfileWithoutTouchingUserSameNameProfile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	original := strings.Join([]string{
		"profile = \"hanhan\"",
		"",
		"[model_providers.hanhan]",
		"name = \"hanhan\"",
		"base_url = \"https://user.example/v1\"",
		"",
		"[profiles.hanhan]",
		"model_provider = \"hanhan\"",
		"model = \"user-model\"",
		"",
	}, "\n")
	if err := os.WriteFile(configPath, []byte(original), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	if _, err := syncer.Sync(domainprofile.Profile{Name: "hanhan", BaseURL: "https://relay.example/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{DefaultProfileName: "hanhan"}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "profile = \"agx/hanhan\"") {
		t.Fatalf("config=%q want namespaced root profile", text)
	}
	if !strings.Contains(text, "[profiles.hanhan]\nmodel_provider = \"hanhan\"\nmodel = \"user-model\"") {
		t.Fatalf("config=%q want user profile preserved", text)
	}
	if !strings.Contains(text, "[profiles.\"agx/hanhan\"]\nmodel_provider = \"agx/hanhan\"") {
		t.Fatalf("config=%q want AGX namespaced profile", text)
	}

	if _, err := syncer.RemoveProfile("hanhan"); err != nil {
		t.Fatalf("RemoveProfile() error = %v", err)
	}
	got, err = os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text = string(got)
	if strings.Contains(text, "[profiles.\"agx/hanhan\"]") || strings.Contains(text, "[model_providers.\"agx/hanhan\"]") {
		t.Fatalf("config=%q want AGX managed profile removed", text)
	}
	if !strings.Contains(text, "[profiles.hanhan]\nmodel_provider = \"hanhan\"\nmodel = \"user-model\"") {
		t.Fatalf("config=%q want user profile still preserved", text)
	}
}

func TestSyncMigratesLegacyBareManagedProfile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	backupsDir := filepath.Join(dir, ".config", "agx", "backups")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	legacy := strings.Join([]string{
		"profile = \"hanhan\"",
		"",
		beginMarker,
		"[model_providers.\"agx/hanhan\"]",
		"name = \"hanhan\"",
		"base_url = \"https://old.example/v1\"",
		"",
		"[profiles.\"hanhan\"]",
		"model_provider = \"agx/hanhan\"",
		"model = \"gpt-5.5\"",
		endMarker,
		"",
	}, "\n")
	if err := os.WriteFile(configPath, []byte(legacy), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	syncer := NewSyncer(configPath, backupsDir, "agx")
	status, err := syncer.Status()
	if err != nil {
		t.Fatalf("Status() error = %v", err)
	}
	if status.DefaultProfileName != "hanhan" {
		t.Fatalf("DefaultProfileName = %q, want hanhan", status.DefaultProfileName)
	}
	if _, ok := status.ManagedProfilesByID["hanhan"]; !ok {
		t.Fatalf("ManagedProfilesByID = %+v, want hanhan legacy managed profile", status.ManagedProfilesByID)
	}

	if _, err := syncer.Sync(domainprofile.Profile{Name: "hanhan", BaseURL: "https://new.example/v1", APIKey: "sk-a"}, ports.CodexSyncOptions{}); err != nil {
		t.Fatalf("Sync() error = %v", err)
	}
	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config) error = %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "profile = \"agx/hanhan\"") || !strings.Contains(text, "[profiles.\"agx/hanhan\"]\nmodel_provider = \"agx/hanhan\"\nmodel = \"gpt-5.5\"") {
		t.Fatalf("config=%q want migrated namespaced profile with extras", text)
	}
	if strings.Contains(text, "[profiles.\"hanhan\"]") {
		t.Fatalf("config=%q want legacy bare profile removed from managed block", text)
	}
}

func TestRemoveConfigDeletesManagedFile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	syncer := NewSyncer(configPath, filepath.Join(dir, ".config", "agx", "backups"), "agx")
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(configPath, []byte("profile = \"temp\"\n"), 0600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	if _, err := syncer.RemoveConfig(); err != nil {
		t.Fatalf("RemoveConfig() error = %v", err)
	}
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config still exists, err = %v", err)
	}
}
